
from psycopg2.extensions import cursor
from TeacherAssistant.utils.database_tools import backup_postgres_db
# All developed models about Educational & Learning materials has been saved here.

# Model layer for item that needs student response and other cases about his/her activity.
# this model modifies teacher's feedback and answer, score, received date of specified edu-item 
class EduItemStudentModel: 
    
    def __init__(self, cursor:cursor):
        
        self.cursor =  cursor

    def update_learning_item(self, Id:int, answer:str, feedback:str, score:float, reply_date:str):
        '''
        `Id`: Unique Id generated by databse engine,<br>
        `answer`: received answer from student(this is saved as html format)<br>
        `feedback`: Teacher's opinion and analysis of the response received fron the student<br>
        `score`: assigned score to an response of the student,<br>
        `reply_date`: The date of the student's response was received by the teacher.<br>
        These data is stored in `quests` table.
        '''

        try:
            cmd = 'UPDATE quests SET answer_ = %s, earned_point_ = %s, reply_date_= %s, feedback_= %s '
            cmd += 'WHERE Id = %s;'

            self.cursor.execute(cmd,(answer, score,  reply_date, feedback, Id))

            status = True
            message =f'All changes of the Edu-Item with Id:{Id} was updated.'

        except Exception as e:
            status = False
            message = f'Database Error: {e}.'

        return status, message

    
    def remove_learning_item(self, database_Id):
        try:
            
            query  = f'DELETE FROM quests WHERE Id ={database_Id};'
            self.cursor.execute(query)

            status = True
            message =f'The Edu-Item with Id:{database_Id} was removed from database.'

        except Exception as e:
            status = False
            message = f'Database Error: {e}.'

        return status, message


class ClassroomGroupModel: 
    
    def __init__(self, cursor:cursor):
        
        self.cursor =  cursor
    
    def delete_group(self, group_id):
        try:
            
            # retreive members of the group already to delete
            self.cursor.execute('SELECT members_ FROM groups WHERE Id =%i;')
            members = self.cursor.fetchone()
            # delete the group
            self.cursor.execute('DELETE FROM groups WHERE Id = %i',(group_id))
            # retreive members of the ungrouped record
            self.cursor.execute('SELECT members_ FROM groups WHERE grade_ =0;')

            ungrouped = self.cursor.fetchone()
            # update ungrouped record by adding members of rmoved group.
            self.cursor.execute('UPDATE groups SET members_ = %s WHERE grade_ = 0;',(f'{ungrouped},{members}'))

            return True, f'The group with Id:{group_id} removed successfully.'
        
        except Exception as e: return False, f'Error: {e}.'
 
    def add_new_group(self,grade,book,title,description):
        try:
            self.cursor.execute("INSERT INTO groups (grade_, book_, title_, events_, members_, description_) VALUES (%s, %s, %s, %s, %s, %s) RETURNING Id;",
                                (grade, book, title,'','', description))
            id = self.cursor.fetchone()
            return True,id, f'New group with Id:{id} created successfully.'
        
        except Exception as e: return False, None, f'Error: {e}.'
    
    def add_member(self, group_id:int, new_members:str):
        
        try:
            # members must be add to the goup
            new_members = new_members.split(',')
            self.cursor.execute('SELECT members_ FROM groups WHERE Id = %s;',(group_id,))
            # members that included in the group
            old_members = str(self.cursor.fetchone()[0])

            self.cursor.execute('SELECT members_ FROM groups WHERE grade_ = 0;')
            
            ungrouped = str(self.cursor.fetchone()[0])
            print('ungrouped:',ungrouped)

            updated_list = old_members
            for s in new_members:
                # If a member is not already in the group, it must be added to the group.
                # also must be removed from ungrouped record
                if old_members.find(s)<0:
                    updated_list = updated_list + ',' + s
                    ungrouped = ungrouped.replace(s,'')

            cmd = 'UPDATE groups SET members_ = %s WHERE Id = %s; UPDATE groups SET members_ = %s WHERE grade_ = 0;'
            self.cursor.execute(cmd,(updated_list, group_id, ungrouped,))
            
            return True, 'The group updated.'
        
        except Exception as e: return False, f'#Error:{e}.'

    def remove_member(self, group_id, member_id):
        pass

    def load_groups(self):
       
        try:
            self.cursor.execute('SELECT id, grade_, book_, title_, events_, members_, description_ FROM groups;')
        
            records = self.cursor.fetchall()
            
            return True, records
        
        except Exception as e: return False, f'Error:{e}.'

class MainTenanceModel:
    def __init__(self):
        pass

    def backup(self, database_name:str,user_name:str, password:str, output_directory:str, host_address:str='loclahost', port:str='5432'):

        backup_postgres_db(dbname= database_name,user=user_name, password=password, host= host_address, port=port,output_dir=output_directory)